version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Running build command..."
      - npm run build
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  name: BuildArtifact