version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies for testing..."
      - npm install
  
  pre_build:
    commands:
      - echo "Pre-test phase started on `date`"
      - echo "Verifying test configuration..."
      - npx jest --version
  
  build:
    commands:
      - echo "Test phase started on `date`"
      - echo "Running tests..."
      - npm test
      - echo "Tests completed on `date`"
  
  post_build:
    commands:
      - echo "Post-test phase"
      - echo "Test results processed successfully"

artifacts:
  files:
    - '**/*'
  name: TestArtifact